name: build and deploy SAM app
on:
  push:
    branches:
      - master
jobs:
  sam-validate-build-test-deploy:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies with Apt Get
        run: |
          sudo apt-get update
          sudo apt-get install python3.8 jq python3-setuptools -y
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: SAM Validate
        run: |
          sam validate
      - name: SAM Build
        run: |
          sam build --use-container
      - name: SAM Deploy
        run: |
          # Run SAM Deploy
          sam deploy --template-file .aws-sam/build/template.yaml \
            --stack-name TimelineToCalendar  \
            --s3-bucket ${{ secrets.AWS_SAM_S3_BUCKET }} \
            --s3-prefix TimelineToCalendar \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides BucketName=google-timeline-to-calendar
